# -*- coding: utf-8 -*-
"""movie-recommender-system.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WLnc7IIALBEZtH3LekEBywqmMpydEvc-

**MOVIE RECOMMENDER SYSTEM**
"""

import numpy as np
import pandas as pd
import joblib

movies = pd.read_csv("tmdb_5000_movies.csv")
credits = pd.read_csv("tmdb_5000_credits.csv")

movies.head()

credits.head()

movies = movies.merge(credits,on='title')

movies.shape

""">Removing the unuseful columns"""

movies.info()

movies = movies[['movie_id','title','overview','genres','keywords','cast','crew']]
movies.head()

"""creating a column of tags usings overview,genres,cast,crew,keywords

"""

movies.isnull().sum()

movies.dropna(inplace=True)

movies.duplicated().sum()

import ast

def convert_genres(obj):
  L = []
  for i in ast.literal_eval(obj):
    L.append(i['name'])
  return L

movies['genres'] = movies['genres'].apply(convert_genres)
movies['genres']

movies['keywords'] = movies['keywords'].apply(convert_genres)
movies['keywords']

def convert_cast(obj):
  L = []
  count=0
  for i in ast.literal_eval(obj):
    if count!=3:
      L.append(i['name'])
      count+=1
    else:
      break
  return L


movies['cast'] = movies['cast'].apply(convert_cast)

movies.head()

def convert_crew(obj):
  L = []
  for i in ast.literal_eval(obj):
    if i['job'] == 'Director':
       L.append(i['name'])
       break
  return L

movies['crew'] = movies['crew'].apply(convert_crew)
movies['crew']

movies['overview'] = movies['overview'].apply(lambda x:x.split())
movies['overview']

movies['cast'] = movies['cast'].apply(lambda x: [i.replace(" ","") for i in x])
movies['crew'] = movies['crew'].apply(lambda x: [i.replace(" ","") for i in x])
movies['genres'] = movies['genres'].apply(lambda x: [i.replace(" ","") for i in x])
movies['keywords'] = movies['keywords'].apply(lambda x: [i.replace(" ","") for i in x])
movies.head()

movies['tags'] = movies['overview'] + movies['genres'] + movies['keywords'] + movies['cast'] + movies['crew']

new_df = movies[['movie_id','title','tags']].copy()
new_df.head()

new_df['tags'] = new_df['tags'].apply(lambda x: " ".join(x).lower())

# !pip install nltk

import nltk
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

def stem(text):
  y = []
  for i in text.split():
    y.append(ps.stem(i))
  return " ".join(y)

new_df['tags'] = new_df['tags'].apply(stem)

new_df['tags']

"""text vectorisation"""

from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000,stop_words='english')

vectors = cv.fit_transform(new_df['tags']).toarray()

cv.get_feature_names_out()

from sklearn.metrics.pairwise import cosine_similarity
similarity = cosine_similarity(vectors)

similarity.shape

"""main function"""

def recommend(movie):
    movie_index = new_df[new_df['title'] == movie].index[0]

    distances = similarity[movie_index]

    movies_list = sorted(
        list(enumerate(distances)),
        reverse=True,
        key=lambda x: x[1]
    )[1:6]

    recommendations = []

    for i in movies_list:
        recommendations.append(new_df.iloc[i[0]].title)

    return recommendations

recommend('Avatar')

joblib.dump(new_df, "movies.pkl")
joblib.dump(similarity, "similarity.pkl")